server:
  port: 8080
logging:
  config: classpath:logback-boot.xml
  file:
    name: logs/spring-boot-logging.log
spring:
  profiles:
    active: dev
# MyBatis配置
mybatis:
  mapper-locations: classpath:/cn/shiro/shiroservice/**/mapper/*.xml  #xml所在的路径
  type-aliases-package: cn.shiro.shiroservice.**.mapper.**  # 实体类所在的包路径

shiro:
  #当用户访问某个需要登录的功能时，但是被shiro内置的过滤器拦截后，判断本次请求
  #没有登录，而是直接访问的，则重定向到loginUrl的路径资源响应给用户
  loginUrl: /login